/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.StyleConstants.FontConstants;
import static javax.swing.text.StyleConstants.FontFamily;

/**
 *
 * @author Dell
 */
public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     * 
     * 
     * 
     * 
     * 
     * 
  */
    
     personal per=new personal();
     education[] edu=new education[20];
     projects[] pro=new projects[20];
     internship[] in=new internship[20];
     workExperience[] wo=new workExperience[20];
     language[] lg=new language[20];
     skills[] sk=new skills[20];
     hobbies hb=new hobbies();
    public Employee() {
        initComponents();
        this.setBounds(160,120,1020,520);
        personal.setBounds(250,50,740,420);
        personal.setVisible(true);
        education.setBounds(250,50,740,420);
        education.setVisible(false);
        
        project.setBounds(250,50,740,420);
        work.setBounds(250,50,740,420);
        //skill.setBounds(250,50,740,420);
        language.setBounds(250,50,740,420);
        language1.setBounds(250,50,740,420);
        //skill.setBounds(250,50,740,420);
         hobbies.setBounds(250,50,740,420);
         internship.setBounds(250,50,740,420);
        // p1.setVisible(false);
        
        project.setVisible(false);
        work.setVisible(false);
        //p5.setVisible(false);
        language1.setVisible(false);
        hobbies.setVisible(false);
        language.setVisible(false);
        internship.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p6 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jTextField45 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        b21 = new javax.swing.JButton();
        b22 = new javax.swing.JButton();
        b23 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        jTextField46 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jTextField47 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jTextField48 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jTextField49 = new javax.swing.JTextField();
        p7 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jTextField50 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        b24 = new javax.swing.JButton();
        b25 = new javax.swing.JButton();
        b26 = new javax.swing.JButton();
        jLabel53 = new javax.swing.JLabel();
        jTextField51 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jTextField52 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jTextField53 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jTextField54 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b31 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        work = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        t42 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt4 = new javax.swing.JTable();
        b15 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        t41 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        t43 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        t44 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        t45 = new javax.swing.JTextField();
        hobbies = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        t81 = new javax.swing.JTextPane();
        personal = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        t20 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        t9 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        t19 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        t10 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        l1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        education = new javax.swing.JPanel();
        t13 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        t12 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        t11 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        t14 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        t15 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt1 = new javax.swing.JTable();
        b8 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        p5 = new javax.swing.JPanel();
        jTextField40 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jTextField41 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField42 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jTextField43 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jTextField44 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        b18 = new javax.swing.JButton();
        b19 = new javax.swing.JButton();
        b20 = new javax.swing.JButton();
        project = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        t22 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        t23 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt2 = new javax.swing.JTable();
        b12 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        t21 = new javax.swing.JTextField();
        internship = new javax.swing.JPanel();
        jLabel70 = new javax.swing.JLabel();
        t32 = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jt3 = new javax.swing.JTable();
        b38 = new javax.swing.JButton();
        b39 = new javax.swing.JButton();
        jLabel72 = new javax.swing.JLabel();
        t31 = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        t33 = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        t34 = new javax.swing.JTextField();
        jLabel75 = new javax.swing.JLabel();
        t35 = new javax.swing.JTextField();
        language = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jt5 = new javax.swing.JTable();
        b27 = new javax.swing.JButton();
        b28 = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        t51 = new javax.swing.JTextField();
        sl1 = new javax.swing.JSlider();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        language1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jt6 = new javax.swing.JTable();
        b29 = new javax.swing.JButton();
        b30 = new javax.swing.JButton();
        jLabel61 = new javax.swing.JLabel();
        t52 = new javax.swing.JTextField();
        sl2 = new javax.swing.JSlider();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();

        p6.setBackground(new java.awt.Color(255, 255, 255));
        p6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p6.setLayout(null);

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(102, 102, 102));
        jLabel47.setText("Employeer");
        p6.add(jLabel47);
        jLabel47.setBounds(380, 50, 80, 15);
        p6.add(jTextField45);
        jTextField45.setBounds(380, 70, 330, 40);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Work Experience");
        p6.add(jLabel21);
        jLabel21.setBounds(320, 20, 120, 20);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "School", "Degree", "Start Date", "End Date", "City"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        p6.add(jScrollPane5);
        jScrollPane5.setBounds(20, 240, 690, 160);

        b21.setBackground(new java.awt.Color(0, 153, 254));
        b21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b21.setForeground(new java.awt.Color(255, 255, 255));
        b21.setText("Add");
        p6.add(b21);
        b21.setBounds(390, 180, 100, 30);

        b22.setBackground(new java.awt.Color(0, 153, 254));
        b22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b22.setForeground(new java.awt.Color(255, 255, 255));
        b22.setText("Delete");
        p6.add(b22);
        b22.setBounds(610, 180, 100, 30);

        b23.setBackground(new java.awt.Color(0, 153, 254));
        b23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b23.setForeground(new java.awt.Color(255, 255, 255));
        b23.setText("Edit");
        p6.add(b23);
        b23.setBounds(500, 180, 100, 30);

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(102, 102, 102));
        jLabel48.setText("Job Title");
        p6.add(jLabel48);
        jLabel48.setBounds(20, 50, 100, 15);
        p6.add(jTextField46);
        jTextField46.setBounds(20, 70, 330, 40);

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(102, 102, 102));
        jLabel49.setText("Start Date");
        p6.add(jLabel49);
        jLabel49.setBounds(20, 110, 80, 15);
        p6.add(jTextField47);
        jTextField47.setBounds(20, 130, 150, 40);

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(102, 102, 102));
        jLabel50.setText("End Date");
        p6.add(jLabel50);
        jLabel50.setBounds(200, 110, 80, 15);
        p6.add(jTextField48);
        jTextField48.setBounds(200, 130, 150, 40);

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(102, 102, 102));
        jLabel51.setText("City");
        p6.add(jLabel51);
        jLabel51.setBounds(380, 110, 80, 15);
        p6.add(jTextField49);
        jTextField49.setBounds(380, 130, 330, 40);

        p7.setBackground(new java.awt.Color(255, 255, 255));
        p7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p7.setLayout(null);

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(102, 102, 102));
        jLabel52.setText("Employeer");
        p7.add(jLabel52);
        jLabel52.setBounds(380, 50, 80, 15);
        p7.add(jTextField50);
        jTextField50.setBounds(380, 70, 330, 40);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Work Experience");
        p7.add(jLabel22);
        jLabel22.setBounds(320, 20, 120, 20);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "School", "Degree", "Start Date", "End Date", "City"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        p7.add(jScrollPane6);
        jScrollPane6.setBounds(20, 240, 690, 160);

        b24.setBackground(new java.awt.Color(0, 153, 254));
        b24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b24.setForeground(new java.awt.Color(255, 255, 255));
        b24.setText("Add");
        p7.add(b24);
        b24.setBounds(390, 180, 100, 30);

        b25.setBackground(new java.awt.Color(0, 153, 254));
        b25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b25.setForeground(new java.awt.Color(255, 255, 255));
        b25.setText("Delete");
        p7.add(b25);
        b25.setBounds(610, 180, 100, 30);

        b26.setBackground(new java.awt.Color(0, 153, 254));
        b26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b26.setForeground(new java.awt.Color(255, 255, 255));
        b26.setText("Edit");
        p7.add(b26);
        b26.setBounds(500, 180, 100, 30);

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(102, 102, 102));
        jLabel53.setText("Job Title");
        p7.add(jLabel53);
        jLabel53.setBounds(20, 50, 100, 15);
        p7.add(jTextField51);
        jTextField51.setBounds(20, 70, 330, 40);

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(102, 102, 102));
        jLabel54.setText("Start Date");
        p7.add(jLabel54);
        jLabel54.setBounds(20, 110, 80, 15);
        p7.add(jTextField52);
        jTextField52.setBounds(20, 130, 150, 40);

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(102, 102, 102));
        jLabel55.setText("End Date");
        p7.add(jLabel55);
        jLabel55.setBounds(200, 110, 80, 15);
        p7.add(jTextField53);
        jTextField53.setBounds(200, 130, 150, 40);

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(102, 102, 102));
        jLabel56.setText("City");
        p7.add(jLabel56);
        jLabel56.setBounds(380, 110, 80, 15);
        p7.add(jTextField54);
        jTextField54.setBounds(380, 130, 330, 40);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        b2.setBackground(new java.awt.Color(0, 153, 254));
        b2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b2.setForeground(new java.awt.Color(255, 255, 255));
        b2.setText("Education");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel3.add(b2);
        b2.setBounds(10, 60, 200, 50);

        b3.setBackground(new java.awt.Color(0, 153, 254));
        b3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b3.setForeground(new java.awt.Color(255, 255, 255));
        b3.setText("Projects");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel3.add(b3);
        b3.setBounds(10, 110, 200, 50);

        b4.setBackground(new java.awt.Color(0, 153, 254));
        b4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b4.setForeground(new java.awt.Color(255, 255, 255));
        b4.setText("Internships");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel3.add(b4);
        b4.setBounds(10, 160, 200, 50);

        b5.setBackground(new java.awt.Color(0, 153, 254));
        b5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b5.setForeground(new java.awt.Color(255, 255, 255));
        b5.setText("Work Experience");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel3.add(b5);
        b5.setBounds(10, 210, 200, 50);

        b6.setBackground(new java.awt.Color(0, 153, 254));
        b6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b6.setForeground(new java.awt.Color(255, 255, 255));
        b6.setText("Languages");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel3.add(b6);
        b6.setBounds(10, 260, 200, 50);

        b7.setBackground(new java.awt.Color(0, 153, 254));
        b7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b7.setForeground(new java.awt.Color(255, 255, 255));
        b7.setText("Skills");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel3.add(b7);
        b7.setBounds(10, 310, 200, 50);

        b9.setBackground(new java.awt.Color(0, 153, 254));
        b9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b9.setForeground(new java.awt.Color(255, 255, 255));
        b9.setText("Hobbies");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        jPanel3.add(b9);
        b9.setBounds(10, 360, 200, 50);

        b31.setBackground(new java.awt.Color(0, 153, 254));
        b31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b31.setForeground(new java.awt.Color(255, 255, 255));
        b31.setText("Personal Information");
        b31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b31ActionPerformed(evt);
            }
        });
        jPanel3.add(b31);
        b31.setBounds(10, 10, 200, 50);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 50, 220, 420);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 153, 244));
        jLabel30.setText("RESUME");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(40, 0, 170, 44);

        b1.setBackground(new java.awt.Color(0, 153, 254));
        b1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 255, 255));
        b1.setText("CREATE CV");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(860, 10, 130, 30);

        work.setBackground(new java.awt.Color(255, 255, 255));
        work.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        work.setLayout(null);

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(102, 102, 102));
        jLabel38.setText("Employeer");
        work.add(jLabel38);
        jLabel38.setBounds(380, 50, 80, 15);
        work.add(t42);
        t42.setBounds(380, 70, 330, 40);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Work Experience");
        work.add(jLabel19);
        jLabel19.setBounds(340, 20, 120, 17);

        jt4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "School", "Degree", "Start Date", "End Date", "City"
            }
        ));
        jScrollPane3.setViewportView(jt4);

        work.add(jScrollPane3);
        jScrollPane3.setBounds(20, 240, 690, 160);

        b15.setBackground(new java.awt.Color(0, 153, 254));
        b15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b15.setForeground(new java.awt.Color(255, 255, 255));
        b15.setText("Add");
        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b15ActionPerformed(evt);
            }
        });
        work.add(b15);
        b15.setBounds(500, 180, 100, 30);

        b16.setBackground(new java.awt.Color(0, 153, 254));
        b16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b16.setForeground(new java.awt.Color(255, 255, 255));
        b16.setText("Delete");
        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16ActionPerformed(evt);
            }
        });
        work.add(b16);
        b16.setBounds(610, 180, 100, 30);

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(102, 102, 102));
        jLabel40.setText("Job Title");
        work.add(jLabel40);
        jLabel40.setBounds(20, 50, 100, 15);
        work.add(t41);
        t41.setBounds(20, 70, 330, 40);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 102, 102));
        jLabel34.setText("Start Date");
        work.add(jLabel34);
        jLabel34.setBounds(20, 110, 80, 15);
        work.add(t43);
        t43.setBounds(20, 130, 150, 40);

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(102, 102, 102));
        jLabel39.setText("End Date");
        work.add(jLabel39);
        jLabel39.setBounds(200, 110, 80, 15);
        work.add(t44);
        t44.setBounds(200, 130, 150, 40);

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(102, 102, 102));
        jLabel41.setText("City");
        work.add(jLabel41);
        jLabel41.setBounds(380, 110, 80, 15);
        work.add(t45);
        t45.setBounds(380, 130, 330, 40);

        jPanel1.add(work);
        work.setBounds(10, 480, 736, 420);

        hobbies.setBackground(new java.awt.Color(255, 255, 255));
        hobbies.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hobbies.setLayout(null);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Hobbies");
        hobbies.add(jLabel25);
        jLabel25.setBounds(350, 20, 80, 20);

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(102, 102, 102));
        jLabel65.setText("Hobbies");
        hobbies.add(jLabel65);
        jLabel65.setBounds(20, 50, 130, 15);

        jScrollPane9.setViewportView(t81);

        hobbies.add(jScrollPane9);
        jScrollPane9.setBounds(20, 70, 690, 170);

        jPanel1.add(hobbies);
        hobbies.setBounds(990, 1300, 740, 420);

        personal.setBackground(new java.awt.Color(255, 255, 255));
        personal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        personal.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Nationality");
        personal.add(jLabel6);
        jLabel6.setBounds(20, 340, 80, 15);
        personal.add(t20);
        t20.setBounds(510, 360, 210, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Address");
        personal.add(jLabel7);
        jLabel7.setBounds(260, 340, 80, 15);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Website");
        personal.add(jLabel12);
        jLabel12.setBounds(510, 340, 80, 15);
        personal.add(t6);
        t6.setBounds(20, 360, 210, 40);
        personal.add(t9);
        t9.setBounds(260, 360, 210, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Phone Number2");
        personal.add(jLabel8);
        jLabel8.setBounds(20, 280, 110, 15);
        personal.add(t5);
        t5.setBounds(20, 300, 210, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Zipcode");
        personal.add(jLabel9);
        jLabel9.setBounds(260, 280, 80, 15);
        personal.add(t8);
        t8.setBounds(260, 300, 210, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Linkedin");
        personal.add(jLabel13);
        jLabel13.setBounds(510, 280, 80, 15);
        personal.add(t19);
        t19.setBounds(510, 300, 210, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Phone Number1");
        personal.add(jLabel10);
        jLabel10.setBounds(20, 220, 110, 15);
        personal.add(t4);
        t4.setBounds(20, 240, 210, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Country");
        personal.add(jLabel11);
        jLabel11.setBounds(260, 220, 80, 15);
        personal.add(t7);
        t7.setBounds(260, 240, 210, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Date Of Birth");
        personal.add(jLabel14);
        jLabel14.setBounds(510, 220, 100, 15);
        personal.add(t10);
        t10.setBounds(510, 240, 210, 40);
        personal.add(t3);
        t3.setBounds(20, 180, 210, 40);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Email");
        personal.add(jLabel15);
        jLabel15.setBounds(20, 160, 80, 15);
        personal.add(t2);
        t2.setBounds(20, 120, 210, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Name");
        personal.add(jLabel16);
        jLabel16.setBounds(20, 100, 80, 15);
        personal.add(t1);
        t1.setBounds(20, 60, 210, 40);

        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setText("Upload here");
        l1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        personal.add(l1);
        l1.setBounds(630, 20, 90, 110);

        jButton1.setBackground(new java.awt.Color(0, 153, 244));
        jButton1.setText("Remove");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        personal.add(jButton1);
        jButton1.setBounds(630, 150, 90, 23);

        jButton2.setBackground(new java.awt.Color(0, 153, 244));
        jButton2.setText("Browse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        personal.add(jButton2);
        jButton2.setBounds(630, 130, 90, 23);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("Personal Information");
        personal.add(jLabel31);
        jLabel31.setBounds(270, 10, 160, 17);

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(102, 102, 102));
        jLabel57.setText("Desired Job");
        personal.add(jLabel57);
        jLabel57.setBounds(20, 40, 80, 15);

        jPanel1.add(personal);
        personal.setBounds(250, 50, 740, 410);

        education.setBackground(new java.awt.Color(255, 255, 255));
        education.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        education.setLayout(null);
        education.add(t13);
        t13.setBounds(20, 130, 150, 40);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("Start Date");
        education.add(jLabel27);
        jLabel27.setBounds(20, 110, 80, 15);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("Degree");
        education.add(jLabel28);
        jLabel28.setBounds(380, 50, 80, 15);
        education.add(t12);
        t12.setBounds(380, 70, 330, 40);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("School");
        education.add(jLabel29);
        jLabel29.setBounds(20, 50, 80, 15);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Education");
        education.add(jLabel17);
        jLabel17.setBounds(340, 20, 80, 17);
        education.add(t11);
        t11.setBounds(20, 70, 330, 40);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(102, 102, 102));
        jLabel32.setText("End Date");
        education.add(jLabel32);
        jLabel32.setBounds(200, 110, 80, 15);
        education.add(t14);
        t14.setBounds(200, 130, 150, 40);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 102, 102));
        jLabel33.setText("City");
        education.add(jLabel33);
        jLabel33.setBounds(380, 110, 80, 15);
        education.add(t15);
        t15.setBounds(380, 130, 330, 40);

        jt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "School", "Degree", "Start Date", "End Date", "City"
            }
        ));
        jScrollPane1.setViewportView(jt1);

        education.add(jScrollPane1);
        jScrollPane1.setBounds(20, 240, 690, 160);

        b8.setBackground(new java.awt.Color(0, 153, 254));
        b8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b8.setForeground(new java.awt.Color(255, 255, 255));
        b8.setText("Add");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        education.add(b8);
        b8.setBounds(500, 180, 100, 30);

        b10.setBackground(new java.awt.Color(0, 153, 254));
        b10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b10.setForeground(new java.awt.Color(255, 255, 255));
        b10.setText("Delete");
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        education.add(b10);
        b10.setBounds(610, 180, 100, 30);

        p5.setBackground(new java.awt.Color(255, 255, 255));
        p5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p5.setLayout(null);
        p5.add(jTextField40);
        jTextField40.setBounds(20, 130, 150, 40);

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(102, 102, 102));
        jLabel42.setText("Start Date");
        p5.add(jLabel42);
        jLabel42.setBounds(20, 110, 80, 15);

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(102, 102, 102));
        jLabel43.setText("Degree");
        p5.add(jLabel43);
        jLabel43.setBounds(380, 50, 80, 15);
        p5.add(jTextField41);
        jTextField41.setBounds(380, 70, 330, 40);

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(102, 102, 102));
        jLabel44.setText("School");
        p5.add(jLabel44);
        jLabel44.setBounds(20, 50, 80, 15);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Education");
        p5.add(jLabel20);
        jLabel20.setBounds(340, 20, 80, 17);
        p5.add(jTextField42);
        jTextField42.setBounds(20, 70, 330, 40);

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(102, 102, 102));
        jLabel45.setText("End Date");
        p5.add(jLabel45);
        jLabel45.setBounds(200, 110, 80, 15);
        p5.add(jTextField43);
        jTextField43.setBounds(200, 130, 150, 40);

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(102, 102, 102));
        jLabel46.setText("City");
        p5.add(jLabel46);
        jLabel46.setBounds(380, 110, 80, 15);
        p5.add(jTextField44);
        jTextField44.setBounds(380, 130, 330, 40);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "School", "Degree", "Start Date", "End Date", "City"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        p5.add(jScrollPane4);
        jScrollPane4.setBounds(20, 240, 690, 160);

        b18.setBackground(new java.awt.Color(0, 153, 254));
        b18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b18.setForeground(new java.awt.Color(255, 255, 255));
        b18.setText("Add");
        p5.add(b18);
        b18.setBounds(390, 180, 100, 30);

        b19.setBackground(new java.awt.Color(0, 153, 254));
        b19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b19.setForeground(new java.awt.Color(255, 255, 255));
        b19.setText("Delete");
        p5.add(b19);
        b19.setBounds(610, 180, 100, 30);

        b20.setBackground(new java.awt.Color(0, 153, 254));
        b20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b20.setForeground(new java.awt.Color(255, 255, 255));
        b20.setText("Edit");
        p5.add(b20);
        b20.setBounds(500, 180, 100, 30);

        education.add(p5);
        p5.setBounds(80, 500, 740, 420);

        jPanel1.add(education);
        education.setBounds(1000, 10, 740, 420);

        project.setBackground(new java.awt.Color(255, 255, 255));
        project.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        project.setLayout(null);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 102, 102));
        jLabel35.setText("Skills Used");
        project.add(jLabel35);
        jLabel35.setBounds(380, 50, 80, 15);
        project.add(t22);
        t22.setBounds(380, 70, 330, 40);

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 102, 102));
        jLabel36.setText("Description");
        project.add(jLabel36);
        jLabel36.setBounds(20, 110, 100, 15);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Projects");
        project.add(jLabel18);
        jLabel18.setBounds(340, 20, 80, 17);
        project.add(t23);
        t23.setBounds(20, 130, 690, 40);

        jt2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Project Name", "Skill Used", "Description"
            }
        ));
        jScrollPane2.setViewportView(jt2);

        project.add(jScrollPane2);
        jScrollPane2.setBounds(20, 240, 690, 160);

        b12.setBackground(new java.awt.Color(0, 153, 254));
        b12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b12.setForeground(new java.awt.Color(255, 255, 255));
        b12.setText("Add");
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });
        project.add(b12);
        b12.setBounds(500, 180, 100, 30);

        b13.setBackground(new java.awt.Color(0, 153, 254));
        b13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b13.setForeground(new java.awt.Color(255, 255, 255));
        b13.setText("Delete");
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });
        project.add(b13);
        b13.setBounds(610, 180, 100, 30);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(102, 102, 102));
        jLabel37.setText("Project Name");
        project.add(jLabel37);
        jLabel37.setBounds(20, 50, 100, 15);
        project.add(t21);
        t21.setBounds(20, 70, 330, 40);

        jPanel1.add(project);
        project.setBounds(1000, 440, 740, 420);

        internship.setBackground(new java.awt.Color(255, 255, 255));
        internship.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        internship.setLayout(null);

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(102, 102, 102));
        jLabel70.setText("Employeer");
        internship.add(jLabel70);
        jLabel70.setBounds(380, 50, 80, 15);
        internship.add(t32);
        t32.setBounds(380, 70, 330, 40);

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel71.setText("Internships");
        internship.add(jLabel71);
        jLabel71.setBounds(340, 20, 80, 17);

        jt3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "School", "Degree", "Start Date", "End Date", "City"
            }
        ));
        jScrollPane11.setViewportView(jt3);

        internship.add(jScrollPane11);
        jScrollPane11.setBounds(20, 240, 690, 160);

        b38.setBackground(new java.awt.Color(0, 153, 254));
        b38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b38.setForeground(new java.awt.Color(255, 255, 255));
        b38.setText("Add");
        b38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b38ActionPerformed(evt);
            }
        });
        internship.add(b38);
        b38.setBounds(500, 180, 100, 30);

        b39.setBackground(new java.awt.Color(0, 153, 254));
        b39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b39.setForeground(new java.awt.Color(255, 255, 255));
        b39.setText("Delete");
        b39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b39ActionPerformed(evt);
            }
        });
        internship.add(b39);
        b39.setBounds(610, 180, 100, 30);

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(102, 102, 102));
        jLabel72.setText("Job Title");
        internship.add(jLabel72);
        jLabel72.setBounds(20, 50, 100, 15);
        internship.add(t31);
        t31.setBounds(20, 70, 330, 40);

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(102, 102, 102));
        jLabel73.setText("Start Date");
        internship.add(jLabel73);
        jLabel73.setBounds(20, 110, 80, 15);
        internship.add(t33);
        t33.setBounds(20, 130, 150, 40);

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(102, 102, 102));
        jLabel74.setText("End Date");
        internship.add(jLabel74);
        jLabel74.setBounds(200, 110, 80, 15);
        internship.add(t34);
        t34.setBounds(200, 130, 150, 40);

        jLabel75.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(102, 102, 102));
        jLabel75.setText("City");
        internship.add(jLabel75);
        jLabel75.setBounds(380, 110, 80, 15);
        internship.add(t35);
        t35.setBounds(380, 130, 330, 40);

        jPanel1.add(internship);
        internship.setBounds(10, 910, 740, 420);

        language.setBackground(new java.awt.Color(255, 255, 255));
        language.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        language.setLayout(null);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Languages");
        language.add(jLabel23);
        jLabel23.setBounds(320, 20, 90, 20);

        jt5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Language", "Skill Level"
            }
        ));
        jScrollPane7.setViewportView(jt5);

        language.add(jScrollPane7);
        jScrollPane7.setBounds(380, 70, 340, 330);

        b27.setBackground(new java.awt.Color(0, 153, 254));
        b27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b27.setForeground(new java.awt.Color(255, 255, 255));
        b27.setText("Add");
        b27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b27ActionPerformed(evt);
            }
        });
        language.add(b27);
        b27.setBounds(240, 200, 100, 30);

        b28.setBackground(new java.awt.Color(0, 153, 254));
        b28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b28.setForeground(new java.awt.Color(255, 255, 255));
        b28.setText("Delete");
        b28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b28ActionPerformed(evt);
            }
        });
        language.add(b28);
        b28.setBounds(240, 240, 100, 30);

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(102, 102, 102));
        jLabel58.setText("Fine");
        language.add(jLabel58);
        jLabel58.setBounds(160, 120, 40, 15);
        language.add(t51);
        t51.setBounds(20, 70, 330, 40);

        sl1.setMajorTickSpacing(10);
        sl1.setMaximum(10);
        sl1.setMinorTickSpacing(10);
        sl1.setPaintLabels(true);
        sl1.setPaintTicks(true);
        language.add(sl1);
        sl1.setBounds(20, 140, 320, 40);

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(102, 102, 102));
        jLabel59.setText("Language Name");
        language.add(jLabel59);
        jLabel59.setBounds(20, 50, 130, 15);

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(102, 102, 102));
        jLabel60.setText("Expert");
        language.add(jLabel60);
        jLabel60.setBounds(300, 120, 50, 15);

        jPanel1.add(language);
        language.setBounds(990, 870, 740, 420);

        language1.setBackground(new java.awt.Color(255, 255, 255));
        language1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        language1.setLayout(null);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Skills");
        language1.add(jLabel24);
        jLabel24.setBounds(340, 20, 90, 20);

        jt6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Skill", "Skill Level"
            }
        ));
        jScrollPane8.setViewportView(jt6);

        language1.add(jScrollPane8);
        jScrollPane8.setBounds(380, 70, 340, 330);

        b29.setBackground(new java.awt.Color(0, 153, 254));
        b29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b29.setForeground(new java.awt.Color(255, 255, 255));
        b29.setText("Add");
        b29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b29ActionPerformed(evt);
            }
        });
        language1.add(b29);
        b29.setBounds(240, 200, 100, 30);

        b30.setBackground(new java.awt.Color(0, 153, 254));
        b30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b30.setForeground(new java.awt.Color(255, 255, 255));
        b30.setText("Delete");
        b30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b30ActionPerformed(evt);
            }
        });
        language1.add(b30);
        b30.setBounds(240, 240, 100, 30);

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(102, 102, 102));
        jLabel61.setText("Fine");
        language1.add(jLabel61);
        jLabel61.setBounds(160, 120, 40, 15);
        language1.add(t52);
        t52.setBounds(20, 70, 330, 40);

        sl2.setMajorTickSpacing(10);
        sl2.setMaximum(10);
        sl2.setMinorTickSpacing(10);
        sl2.setPaintLabels(true);
        sl2.setPaintTicks(true);
        language1.add(sl2);
        sl2.setBounds(20, 140, 320, 40);

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(102, 102, 102));
        jLabel62.setText("Skills");
        language1.add(jLabel62);
        jLabel62.setBounds(20, 50, 130, 15);

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(102, 102, 102));
        jLabel63.setText("Expert");
        language1.add(jLabel63);
        jLabel63.setBounds(300, 120, 50, 15);

        jPanel1.add(language1);
        language1.setBounds(10, 1340, 740, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1788, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        personal.setVisible(false);
        education.setVisible(false);
        project.setVisible(false);
        work.setVisible(false);
        language1.setVisible(false);
        internship.setVisible(false);
        hobbies.setVisible(false);
        language.setVisible(true);
    }//GEN-LAST:event_b6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser file=new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter=new FileNameExtensionFilter("*.Images","jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int result=file.showSaveDialog(null);
        if(result==JFileChooser.APPROVE_OPTION)
        {
            File selectedFile=file.getSelectedFile();
            String path=selectedFile.getAbsolutePath();
            l1.setIcon(ResizeImage(path));
        }
        else if(result==JFileChooser.CANCEL_OPTION)
        {
            System.out.println("No File Selected");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        //personal.setVisible(true);
        per.job=t1.getText();
        per.name=t2.getText();
        per.email=t3.getText();
        per.phone1=t4.getText();
        per.phone2=t5.getText();
        per.nationality=t6.getText();
        per.country=t7.getText();
        per.zipcode=t8.getText();
        per.address=t9.getText();
        per.date=t10.getText();
        per.linkdein=t19.getText();
        per.website=t20.getText();
        
        int r1= jt1.getRowCount();
        TableModel model1=jt1.getModel();
        for(int i=0;i<r1;i++)
        {
            edu[i]=new education();
            edu[i].school=model1.getValueAt(i, 0).toString();
            edu[i].degree=model1.getValueAt(i, 1).toString();
            edu[i].startdate=model1.getValueAt(i, 2).toString();
            edu[i].enddate=model1.getValueAt(i, 3).toString();
            edu[i].city=model1.getValueAt(i, 4).toString();
             //System.out.println(edu[i].school+" "+edu[i].degree+" "+edu[i].startdate+" "+edu[i].enddate+" "+edu[i].city+'\n');
        }
       
        int r2= jt2.getRowCount();
        TableModel model2=jt2.getModel();
        for(int i=0;i<r2;i++)
        {
            pro[i]=new projects();
            pro[i].projectname=model2.getValueAt(i, 0).toString();
            pro[i].skill=model2.getValueAt(i, 1).toString();
            pro[i].description=model2.getValueAt(i, 2).toString();
            //System.out.print(""+pro[i].projectname);
        }
        

        int r3= jt3.getRowCount();
        TableModel model3=jt3.getModel();
        for(int i=0;i<r3;i++)
        {
            in[i]=new internship();
            in[i].jobtitle=model3.getValueAt(i, 0).toString();
            in[i].employeer=model3.getValueAt(i, 1).toString();
            in[i].startdate=model3.getValueAt(i, 2).toString(); 
            in[i].enddate=model3.getValueAt(i, 3).toString();
            in[i].city=model3.getValueAt(i, 4).toString();
            //System.out.print(""+in[i].jobtitle+'\n');
            
        }
       
        int r4= jt4.getRowCount();
        //System.out.println(r4+"");
        TableModel model4=jt4.getModel();
        for(int i=0;i<r4;i++)
        {
            wo[i]=new workExperience();
            wo[i].jobtitle=model4.getValueAt(i, 0).toString();
            wo[i].employeer=model4.getValueAt(i, 1).toString();
            wo[i].startdate=model4.getValueAt(i, 2).toString();
            wo[i].enddate=model4.getValueAt(i, 3).toString();
            wo[i].city=model4.getValueAt(i, 4).toString();
            //System.out.println(wo[i].jobtitle+" "+wo[i].employeer+" "+wo[i].startdate+" "+wo[i].enddate+" "+wo[i].city);
            
        }
        
        int r5= jt5.getRowCount();
        TableModel model5=jt5.getModel();
        for(int i=0;i<r5;i++)
        {
            lg[i]=new language();
            lg[i].language=model5.getValueAt(i, 0).toString();
            lg[i].skilllevel=model5.getValueAt(i, 1).toString();
            //System.out.print(lg[i].language+'\n');  
                    }

        
        int r6= jt6.getRowCount();
        TableModel model6=jt6.getModel();
        for(int i=0;i<r6;i++)
        {
            sk[i]=new skills();
             sk[i].skill=model6.getValueAt(i, 0).toString();
            sk[i].skilllevel=model6.getValueAt(i, 1).toString();
            //System.out.print(""+sk[i].skill+'\n');
        }
        
        hb.hobby=t81.getText();
        //System.out.print(h)
        
        
        
         try{
            Document d = new Document();
            PdfWriter writer=PdfWriter.getInstance((com.itextpdf.text.Document) d,new FileOutputStream("C:\\Users\\Dell\\Desktop\\java PDF\\Resume.pdf"));
            System.out.print("pdf Created");
            d.open();
            Paragraph p=new Paragraph(per.name);
            p.setAlignment(Element.ALIGN_LEFT);
            d.add(p);
            p=new Paragraph("--------------------------------------------------------------------------------------------------------------------------------");
            d.add(p);
            p=new Paragraph(per.address+" | "+per.country+" | "+per.zipcode+" | "+per.phone1+" | "+per.email);
            d.add(p);
            p=new Paragraph("\n \n");
            d.add(p);
            p=new Paragraph("EDUCATION");
            p.setAlignment(Element.ALIGN_LEFT);
            d.add(p);
            for(int i=0;i<r1;i++)
            {
                p=new Paragraph(edu[i].school+"        "+edu[i].degree+"        "+edu[i].city+"                                              "+edu[i].startdate+"  -  "+edu[i].enddate);
                p.setAlignment(Element.ALIGN_LEFT);
                d.add(p);
            }
//             p=new Paragraph("\n ");
//            d.add(p);
           
               p=new Paragraph("\n \n");
            d.add(p);
            p=new Paragraph("PROJECTS");
            p.setAlignment(Element.ALIGN_LEFT);
            d.add(p);
            for(int i=0;i<r2;i++)
            {
                p=new Paragraph(pro[i].projectname+"        "+pro[i].skill+"        "+pro[i].description);
                p.setAlignment(Element.ALIGN_LEFT);
                d.add(p);
            }
             p=new Paragraph("\n \n");
            d.add(p);
            p=new Paragraph("INTERNSHIPS");
            p.setAlignment(Element.ALIGN_LEFT);
            d.add(p);
            for(int i=0;i<r3;i++)
            {
                p=new Paragraph(in[i].jobtitle+"        "+in[i].employeer+"        "+in[i].city+"        "+"                                       "+in[i].startdate+"  -  "+in[i].enddate);
                p.setAlignment(Element.ALIGN_LEFT);
                d.add(p);
            }
              p=new Paragraph("\n \n");
            d.add(p);
            p=new Paragraph("WORK EXPERIENCE");
            p.setAlignment(Element.ALIGN_LEFT);
            d.add(p);
            for(int i=0;i<r4;i++)
            {
                p=new Paragraph(wo[i].jobtitle+"        "+wo[i].employeer+"        "+wo[i].city+"        "+"                                       "+wo[i].startdate+"  -  "+wo[i].enddate);
                p.setAlignment(Element.ALIGN_LEFT);
                d.add(p);
            }
               p=new Paragraph("\n \n");
            d.add(p);
            p=new Paragraph("LANGUAGE");
            p.setAlignment(Element.ALIGN_LEFT);
            d.add(p);
            for(int i=0;i<r5;i++)
            {
                p=new Paragraph(lg[i].language+"        "+lg[i].skilllevel);
                p.setAlignment(Element.ALIGN_LEFT);
                d.add(p);
            }
                p=new Paragraph("\n \n");
            d.add(p);
            p=new Paragraph("SKILLS");
            p.setAlignment(Element.ALIGN_LEFT);
            d.add(p);
            for(int i=0;i<r6;i++)
            {
                p=new Paragraph(sk[i].skill+"        "+sk[i].skilllevel);
                p.setAlignment(Element.ALIGN_LEFT);
                d.add(p);
            }
               p=new Paragraph("\n \n");
            d.add(p);
            p=new Paragraph("HOBBIES");
            p.setAlignment(Element.ALIGN_LEFT);
            d.add(p);
            p=new Paragraph(hb.hobby);
            d.close();
            writer.close();
            
            
        }
        catch(FileNotFoundException e)
        {
            
        } catch (DocumentException ex) {
            Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        //ystem.out.print("Ayu");
        personal.setVisible(false);
        education.setVisible(true);
        project.setVisible(false);
        work.setVisible(false);
        language1.setVisible(false);
        internship.setVisible(false);
        hobbies.setVisible(false);
        language.setVisible(false);
    }//GEN-LAST:event_b2ActionPerformed

    private void b31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b31ActionPerformed
        // TODO add your handling code here:
        personal.setBounds(250,50,740,420);
        personal.setVisible(true);
        education.setVisible(false);
        project.setVisible(false);
        work.setVisible(false);
        language1.setVisible(false);
        internship.setVisible(false);
        hobbies.setVisible(false);
        language.setVisible(false);
        
    }//GEN-LAST:event_b31ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        String s1=t11.getText();
        String s2=t12.getText();
        String s3=t13.getText();
        String s4=t14.getText();
        String s5=t15.getText();
        DefaultTableModel df=(DefaultTableModel)jt1.getModel();
           Object obj[]={s1,s2,s3,s4,s5};
           df.addRow(obj);
        t11.setText("");
        t12.setText("");
        t13.setText("");
        t14.setText("");
        t15.setText(""); 
    }//GEN-LAST:event_b8ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        // TODO add your handling code here:
          int r=jt1.getSelectedRow();
       TableModel model=jt1.getModel();
       DefaultTableModel df=(DefaultTableModel)jt1.getModel();
       df.removeRow(jt1.getSelectedRow());
    }//GEN-LAST:event_b10ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
        // TODO add your handling code here:
        String s1=t21.getText();
        String s2=t22.getText();
        String s3=t23.getText();
        DefaultTableModel df=(DefaultTableModel)jt2.getModel();
           Object obj[]={s1,s2,s3};
           df.addRow(obj);
        t21.setText("");
        t22.setText("");
        t23.setText("");
    }//GEN-LAST:event_b12ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
        // TODO add your handling code here:
             int r=jt2.getSelectedRow();
       TableModel model=jt2.getModel();
       DefaultTableModel df=(DefaultTableModel)jt2.getModel();
       df.removeRow(jt2.getSelectedRow());
    }//GEN-LAST:event_b13ActionPerformed

    private void b38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b38ActionPerformed
        // TODO add your handling code here:
        String s1=t31.getText();
        String s2=t32.getText();
        String s3=t33.getText();
        String s4=t34.getText();
        String s5=t35.getText();
        DefaultTableModel df=(DefaultTableModel)jt3.getModel();
           Object obj[]={s1,s2,s3,s4,s5};
           df.addRow(obj);
        t31.setText("");
        t32.setText("");
        t33.setText("");
          t34.setText("");
        t35.setText("");
    }//GEN-LAST:event_b38ActionPerformed

    private void b39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b39ActionPerformed
        // TODO add your handling code here:
                int r=jt3.getSelectedRow();
       TableModel model=jt3.getModel();
       DefaultTableModel df=(DefaultTableModel)jt3.getModel();
       df.removeRow(jt3.getSelectedRow());
    }//GEN-LAST:event_b39ActionPerformed

    private void b27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b27ActionPerformed
        // TODO add your handling code here:
        String s1=t51.getText();
        int k=sl1.getValue();
        DefaultTableModel df=(DefaultTableModel)jt5.getModel();
           Object obj[]={s1,k};
           df.addRow(obj);
        t51.setText("");
    }//GEN-LAST:event_b27ActionPerformed

    private void b28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b28ActionPerformed
        // TODO add your handling code here:
                   int r=jt5.getSelectedRow();
       TableModel model=jt5.getModel();
       DefaultTableModel df=(DefaultTableModel)jt5.getModel();
       df.removeRow(jt5.getSelectedRow());
    }//GEN-LAST:event_b28ActionPerformed

    private void b15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b15ActionPerformed
        // TODO add your handling code here:
          String s1=t41.getText();
        String s2=t42.getText();
        String s3=t43.getText();
        String s4=t44.getText();
        String s5=t45.getText();
        DefaultTableModel df=(DefaultTableModel)jt4.getModel();
           Object obj[]={s1,s2,s3,s4,s5};
           df.addRow(obj);
        t41.setText("");
        t42.setText("");
        t43.setText("");
        t44.setText("");
        t45.setText(""); 
    }//GEN-LAST:event_b15ActionPerformed

    private void b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16ActionPerformed
        // TODO add your handling code here:
                      int r=jt4.getSelectedRow();
       TableModel model=jt4.getModel();
       DefaultTableModel df=(DefaultTableModel)jt4.getModel();
       df.removeRow(jt4.getSelectedRow());
    }//GEN-LAST:event_b16ActionPerformed

    private void b29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b29ActionPerformed
        // TODO add your handling code here:
              String s1=t52.getText();
        int k=sl2.getValue();
        DefaultTableModel df=(DefaultTableModel)jt6.getModel();
           Object obj[]={s1,k};
           df.addRow(obj);
        t52.setText("");
    }//GEN-LAST:event_b29ActionPerformed

    private void b30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b30ActionPerformed
        // TODO add your handling code here:
                          int r=jt6.getSelectedRow();
       TableModel model=jt6.getModel();
       DefaultTableModel df=(DefaultTableModel)jt6.getModel();
       df.removeRow(jt6.getSelectedRow());
    }//GEN-LAST:event_b30ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
//       
personal.setVisible(false);
        education.setVisible(false);
        project.setVisible(false);
        work.setVisible(true);
        language1.setVisible(false);
        internship.setVisible(false);
        hobbies.setVisible(false);
        language.setVisible(false);
    }//GEN-LAST:event_b5ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
//          work.setVisible(false);
//        hobbies.setVisible(true);
personal.setVisible(false);
        education.setVisible(false);
        project.setVisible(false);
        work.setVisible(false);
        language1.setVisible(false);
        internship.setVisible(false);
        hobbies.setVisible(true);
        language.setVisible(false);
    }//GEN-LAST:event_b9ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        personal.setVisible(false);
        education.setVisible(false);
        project.setVisible(true);
        work.setVisible(false);
        language1.setVisible(false);
        internship.setVisible(false);
        hobbies.setVisible(false);
        language.setVisible(false);
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        personal.setVisible(false);
        education.setVisible(false);
        project.setVisible(false);
        work.setVisible(false);
        language1.setVisible(false);
        internship.setVisible(true);
        hobbies.setVisible(false);
        language.setVisible(false);
    }//GEN-LAST:event_b4ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        personal.setVisible(false);
        education.setVisible(false);
        project.setVisible(false);
        work.setVisible(false);
        language1.setVisible(true);
        internship.setVisible(false);
        hobbies.setVisible(false);
        language.setVisible(false);
    }//GEN-LAST:event_b7ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public ImageIcon ResizeImage(String ImagePath)
    {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img=MyImage.getImage();
        Image newImg = img.getScaledInstance(l1.getWidth(),l1.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image=new ImageIcon(newImg);
        return image;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    
      public class personal
{
    String job;
    String name;
    String email;
    String phone1;
    String phone2;
    String nationality;
    String country;
    String zipcode;
    String address;
    String date;
    String linkdein;
    String website;
    
}
      
       public class education
{
    String school;
    String degree;
    String startdate;
    String enddate;
    String city;
    education()
    {
        school="";
        degree="";
        startdate="";
        enddate="";
        city="";
    }
}     
       
    public class projects
{
    String projectname;
    String skill;
    String description;
    
}   
       public class internship
{
    String jobtitle;
    String employeer;
    String startdate;
    String enddate;
    String city;
}     
      public class workExperience
{
    String jobtitle;
    String employeer;
    String startdate;
    String enddate;
    String city;
}       
         public class language
{
    String language;
    String skilllevel;
    
}      
         
         public class skills
{
    String skill;
    String skilllevel;
    
}        
             public class hobbies
{
    String hobby;
    
    
}      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b18;
    private javax.swing.JButton b19;
    private javax.swing.JButton b2;
    private javax.swing.JButton b20;
    private javax.swing.JButton b21;
    private javax.swing.JButton b22;
    private javax.swing.JButton b23;
    private javax.swing.JButton b24;
    private javax.swing.JButton b25;
    private javax.swing.JButton b26;
    private javax.swing.JButton b27;
    private javax.swing.JButton b28;
    private javax.swing.JButton b29;
    private javax.swing.JButton b3;
    private javax.swing.JButton b30;
    private javax.swing.JButton b31;
    private javax.swing.JButton b38;
    private javax.swing.JButton b39;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JPanel education;
    private javax.swing.JPanel hobbies;
    private javax.swing.JPanel internship;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    private javax.swing.JTable jt1;
    private javax.swing.JTable jt2;
    private javax.swing.JTable jt3;
    private javax.swing.JTable jt4;
    private javax.swing.JTable jt5;
    private javax.swing.JTable jt6;
    private javax.swing.JLabel l1;
    private javax.swing.JPanel language;
    private javax.swing.JPanel language1;
    private javax.swing.JPanel p5;
    private javax.swing.JPanel p6;
    private javax.swing.JPanel p7;
    private javax.swing.JPanel personal;
    private javax.swing.JPanel project;
    private javax.swing.JSlider sl1;
    private javax.swing.JSlider sl2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t12;
    private javax.swing.JTextField t13;
    private javax.swing.JTextField t14;
    private javax.swing.JTextField t15;
    private javax.swing.JTextField t19;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t20;
    private javax.swing.JTextField t21;
    private javax.swing.JTextField t22;
    private javax.swing.JTextField t23;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t31;
    private javax.swing.JTextField t32;
    private javax.swing.JTextField t33;
    private javax.swing.JTextField t34;
    private javax.swing.JTextField t35;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t41;
    private javax.swing.JTextField t42;
    private javax.swing.JTextField t43;
    private javax.swing.JTextField t44;
    private javax.swing.JTextField t45;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t51;
    private javax.swing.JTextField t52;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextPane t81;
    private javax.swing.JTextField t9;
    private javax.swing.JPanel work;
    // End of variables declaration//GEN-END:variables
}
