/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */

public class loginpage extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    
    int ayushi=0;
    public loginpage() {
        
        initComponents();
        this.setBounds(160,120,1020,520);
        p1.setBounds(0,0,1010,490);
        p1.setVisible(true);
        p2.setBounds(0,0,1010,490);
        p2.setVisible(false);
        p3.setBounds(0,0,1010,490);
         p3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JPanel();
        b32 = new javax.swing.JButton();
        b31 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        p3 = new javax.swing.JPanel();
        b33 = new javax.swing.JButton();
        b34 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        t23 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        t24 = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        t21 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        t22 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        p2 = new javax.swing.JPanel();
        b41 = new javax.swing.JButton();
        b42 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        t11 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        t12 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        p1.setBackground(new java.awt.Color(255, 255, 255));
        p1.setLayout(null);

        b32.setBackground(new java.awt.Color(0, 153, 254));
        b32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b32.setForeground(new java.awt.Color(255, 255, 255));
        b32.setText("Register");
        b32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b32ActionPerformed(evt);
            }
        });
        p1.add(b32);
        b32.setBounds(560, 370, 200, 50);

        b31.setBackground(new java.awt.Color(0, 153, 254));
        b31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b31.setForeground(new java.awt.Color(255, 255, 255));
        b31.setText("Login ");
        b31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b31ActionPerformed(evt);
            }
        });
        p1.add(b31);
        b31.setBounds(250, 370, 200, 50);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 153, 244));
        jLabel30.setText("RESUME");
        p1.add(jLabel30);
        jLabel30.setBounds(430, 260, 170, 44);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\logoassignment.jpg")); // NOI18N
        p1.add(jLabel1);
        jLabel1.setBounds(430, 120, 130, 120);

        getContentPane().add(p1);
        p1.setBounds(0, 0, 1010, 490);

        p3.setBackground(new java.awt.Color(255, 255, 255));
        p3.setLayout(null);

        b33.setBackground(new java.awt.Color(0, 153, 254));
        b33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b33.setForeground(new java.awt.Color(255, 255, 255));
        b33.setText("Register");
        b33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b33ActionPerformed(evt);
            }
        });
        p3.add(b33);
        b33.setBounds(260, 380, 210, 50);

        b34.setBackground(new java.awt.Color(0, 153, 254));
        b34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b34.setForeground(new java.awt.Color(255, 255, 255));
        b34.setText("Login ");
        b34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b34ActionPerformed(evt);
            }
        });
        p3.add(b34);
        b34.setBounds(560, 380, 200, 50);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 153, 244));
        jLabel31.setText("REGISTER");
        p3.add(jLabel31);
        jLabel31.setBounds(420, 180, 170, 44);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\logoassignment.jpg")); // NOI18N
        p3.add(jLabel2);
        jLabel2.setBounds(430, 40, 130, 120);

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(102, 102, 102));
        jLabel57.setText("Phone/Mobile");
        p3.add(jLabel57);
        jLabel57.setBounds(260, 310, 110, 15);
        p3.add(t23);
        t23.setBounds(260, 330, 210, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Password");
        p3.add(jLabel16);
        jLabel16.setBounds(560, 310, 80, 15);
        p3.add(t24);
        t24.setBounds(560, 330, 200, 40);

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(102, 102, 102));
        jLabel65.setText("Name");
        p3.add(jLabel65);
        jLabel65.setBounds(260, 240, 80, 15);
        p3.add(t21);
        t21.setBounds(260, 260, 210, 40);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Email");
        p3.add(jLabel24);
        jLabel24.setBounds(560, 240, 80, 15);
        p3.add(t22);
        t22.setBounds(560, 260, 200, 40);

        jButton2.setText("<-");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        p3.add(jButton2);
        jButton2.setBounds(0, 0, 50, 23);

        getContentPane().add(p3);
        p3.setBounds(0, 1010, 1010, 490);

        p2.setBackground(new java.awt.Color(255, 255, 255));
        p2.setLayout(null);

        b41.setBackground(new java.awt.Color(0, 153, 254));
        b41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b41.setForeground(new java.awt.Color(255, 255, 255));
        b41.setText("Register");
        b41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b41ActionPerformed(evt);
            }
        });
        p2.add(b41);
        b41.setBounds(260, 380, 210, 50);

        b42.setBackground(new java.awt.Color(0, 153, 254));
        b42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b42.setForeground(new java.awt.Color(255, 255, 255));
        b42.setText("Login ");
        b42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b42ActionPerformed(evt);
            }
        });
        p2.add(b42);
        b42.setBounds(560, 380, 200, 50);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 153, 244));
        jLabel35.setText("LOG IN");
        p2.add(jLabel35);
        jLabel35.setBounds(420, 180, 170, 44);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Downloads\\logoassignment.jpg")); // NOI18N
        p2.add(jLabel6);
        jLabel6.setBounds(430, 40, 130, 120);

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(102, 102, 102));
        jLabel61.setText("Email");
        p2.add(jLabel61);
        jLabel61.setBounds(260, 310, 80, 15);
        p2.add(t11);
        t11.setBounds(260, 330, 210, 40);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Password");
        p2.add(jLabel20);
        jLabel20.setBounds(560, 310, 80, 15);
        p2.add(t12);
        t12.setBounds(560, 330, 200, 40);

        jButton1.setText("<-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        p2.add(jButton1);
        jButton1.setBounds(0, 0, 50, 23);

        getContentPane().add(p2);
        p2.setBounds(0, 510, 1010, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b31ActionPerformed
        // TODO add your handling code here:
     p1.setVisible(false);
     p2.setVisible(true);

    }//GEN-LAST:event_b31ActionPerformed

    private void b32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b32ActionPerformed
        // TODO add your handling code here:
        ayushi=1;
      p1.setVisible(false);
     p3.setVisible(true);

    }//GEN-LAST:event_b32ActionPerformed

    private void b34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b34ActionPerformed

    private void b33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b33ActionPerformed
        // TODO add your handling code here:
         if("".equals(t21.getText()) || t22.getText()=="" || t23.getText()=="" || t24.getText()=="")
        {
            JOptionPane.showMessageDialog(this,"Please add information");
        }
        else{
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/resume","root","");
                Statement st=c.createStatement();
                int i=st.executeUpdate("insert into login values ('"+t21.getText()+"','"+t22.getText()+"','"+t23.getText()+"' ,'"+t24.getText()+"')");
                // System.out.print("check");
                if(i==1)
                {
                    t21.setText("");
                    t22.setText("");
                    t23.setText("");
                    t24.setText("");
                    JOptionPane.showMessageDialog(this,"Registered succesfully");
                    int a= JOptionPane.showConfirmDialog(this,"Do you want to go to login page ?", "choose",JOptionPane.YES_NO_CANCEL_OPTION);
           if(a==JOptionPane.YES_OPTION)
            {
               p2.setVisible(true);
               p3.setVisible(false);
            }

                }
            }
            catch(HeadlessException | ClassNotFoundException | SQLException e)
            {
                System.out.print(e);
            }
        }
    }//GEN-LAST:event_b33ActionPerformed

    private void b41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b41ActionPerformed
        // TODO add your handling code here:
        ayushi=2;
        p3.setVisible(true);
        p2.setVisible(false);
    }//GEN-LAST:event_b41ActionPerformed

    private void b42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b42ActionPerformed
        // TODO add your handling code here:
       String u=t11.getText();
        String p=t12.getText();
        if(u.equals("") || p.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Fill Your informtion");
        }
        else
        {
         try
       {
           Class.forName("com.mysql.jdbc.Driver");
           Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/resume","root","");
           Statement st=c.createStatement();
           ResultSet rs = st.executeQuery("select * from login where email='"+u+"' and password='"+p+"'");
           if(rs.next())
           {
             Employee e=new Employee();
             e.setVisible(true);
           }
           else
           {
              JOptionPane.showMessageDialog(this,"Incorrect informtion");
           }
            
       }
       catch(Exception e)
       {
           System.out.print(e);
       }
        }
    }//GEN-LAST:event_b42ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        p1.setVisible(true);
        p2.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(ayushi==1)
        {
            p1.setVisible(true);
            p3.setVisible(false);
        }
        if(ayushi==2)
        {
            p2.setVisible(true);
            p3.setVisible(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b31;
    private javax.swing.JButton b32;
    private javax.swing.JButton b33;
    private javax.swing.JButton b34;
    private javax.swing.JButton b41;
    private javax.swing.JButton b42;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t12;
    private javax.swing.JTextField t21;
    private javax.swing.JTextField t22;
    private javax.swing.JTextField t23;
    private javax.swing.JTextField t24;
    // End of variables declaration//GEN-END:variables
}
